#!/usr/bin/env python3
"""Generate static font instances for the PDF build.

Two reasons the PDF cannot use the fonts embedded in index.html directly:
1. Chromium's PDF export embeds variable fonts as Type 3 with quantized
   glyph advances (spurious gaps like "Kit chen, f ull ref resh").
2. The subset fonts embedded in index.html carry damaged variation data —
   instances away from the default weight render with broken advances even
   in the browser.

So this script instances the official upstream variable fonts (in
scripts/fonts-src/, from github.com/google/fonts) at the weights the site
uses, and writes them as data-URI @font-face rules the build injects.

Usage: python3 scripts/make-static-fonts.py
Writes: scripts/fonts-static.css
"""
import base64
import io
import os

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'fonts-src')
OUT = os.path.join(HERE, 'fonts-static.css')

# (source file, css family, css style, axis pins per weight, weights)
JOBS = [
    ('Archivo-VF.ttf', 'Archivo', 'normal', {'wdth': 100}, [400, 600, 700, 800]),
    ('SourceSerif4-VF.ttf', 'Source Serif 4', 'normal', {'opsz': 20}, [400, 600, 700]),
    ('SourceSerif4-Italic-VF.ttf', 'Source Serif 4', 'italic', {'opsz': 20}, [400]),
]

rules = []
for filename, family, style, pins, weights in JOBS:
    raw = open(os.path.join(SRC, filename), 'rb').read()
    for w in weights:
        font = TTFont(io.BytesIO(raw))
        instantiateVariableFont(font, {**pins, 'wght': w}, inplace=True)
        buf = io.BytesIO()
        font.save(buf)
        rules.append((family, str(w), style, base64.b64encode(buf.getvalue()).decode()))
        print(f'{family} {style} {w}: {len(buf.getvalue()) // 1024} KB')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('/* generated by make-static-fonts.py — static instances of the\n'
            '   official variable fonts in fonts-src/, for the PDF build */\n')
    for family, weight, style, b64 in rules:
        f.write(
            '@font-face {\n'
            f"  font-family: '{family}';\n"
            f'  font-weight: {weight};\n'
            f'  font-style: {style};\n'
            f'  src: url(data:font/ttf;base64,{b64}) format("truetype");\n'
            '}\n'
        )
print(f'wrote {OUT}')
